In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv("Data.csv")

In [4]:
X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:, -1].values

In [11]:
print (X)
print ("--------------------------\n",Y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
--------------------------
 ['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [16]:
#filling missing values with most_frequent

from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan,strategy='most_frequent')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [17]:
print (X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 48000.0]
 ['France' 35.0 58000.0]
 ['Spain' 27.0 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [18]:
#encoding the categorial values

In [24]:
#encoding the independent values with oneHotEncoding

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0],)],remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [25]:
print (X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 48000.0]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 27.0 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [26]:
# encoding the dependent values with labelencoding

In [29]:
from sklearn.preprocessing import LabelEncoder

lb = LabelEncoder()
Y = lb.fit_transform(Y)

In [30]:
print (Y)

[0 1 0 0 1 1 0 1 0 1]


In [32]:
f_table = np.column_stack((X,Y))
print (f_table)

[[1.0 0.0 0.0 44.0 72000.0 0]
 [0.0 0.0 1.0 27.0 48000.0 1]
 [0.0 1.0 0.0 30.0 54000.0 0]
 [0.0 0.0 1.0 38.0 61000.0 0]
 [0.0 1.0 0.0 40.0 48000.0 1]
 [1.0 0.0 0.0 35.0 58000.0 1]
 [0.0 0.0 1.0 27.0 52000.0 0]
 [1.0 0.0 0.0 48.0 79000.0 1]
 [0.0 1.0 0.0 50.0 83000.0 0]
 [1.0 0.0 0.0 37.0 67000.0 1]]


In [33]:
# splitting training and testing data 

In [41]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2,random_state = 1)

In [42]:
print (X_train)

[[0.0 0.0 1.0 27.0 52000.0]
 [0.0 1.0 0.0 40.0 48000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [43]:
print (X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [44]:
print (Y_train)

[0 1 0 0 1 1 0 1]


In [45]:
print (Y_test)

[0 1]
