In [1]:
#importing libraries

import numpy as np 
import pandas as pd

In [2]:
#dataset
dataset = pd.read_csv("Data.csv")
X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:, -1].values

In [3]:
#filling missing values in dataset

from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan,strategy='constant',fill_value=0)
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])
print (X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 0]
 ['France' 35.0 58000.0]
 ['Spain' 0 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [4]:
#encoding the categorial data

In [5]:
##encoding the categorial data of independent variables

In [7]:
## using HOT ENCODING 
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print (X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 0]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 0 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [8]:
## encoding the categorial data of depending variables

In [12]:
##using LABEL ENCODING
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
Y = le.fit_transform(Y)
print (Y)

[0 1 0 0 1 1 0 1 0 1]


In [13]:
#splitting the data for train & test

In [21]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2,random_state=1)

In [22]:
print (X_train)

[[0.0 0.0 1.0 0 52000.0]
 [0.0 1.0 0.0 40.0 0]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [23]:
print (X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [24]:
print (Y_train)

[0 1 0 0 1 1 0 1]


In [25]:
print (Y_test)

[0 1]


In [26]:
# applying feature scaling

In [27]:
from sklearn.preprocessing import MinMaxScaler

mms = MinMaxScaler()
X_train[:,3:] = mms.fit_transform(X_train[:, 3:])
X_test[:,3:] = mms.transform(X_test[:, 3:])

In [28]:
print (X_train)

[[0.0 0.0 1.0 0.0 0.6265060240963856]
 [0.0 1.0 0.0 0.8 0.0]
 [1.0 0.0 0.0 0.88 0.8674698795180722]
 [0.0 0.0 1.0 0.76 0.7349397590361445]
 [0.0 0.0 1.0 0.54 0.5783132530120482]
 [1.0 0.0 0.0 0.96 0.9518072289156626]
 [0.0 1.0 0.0 1.0 1.0]
 [1.0 0.0 0.0 0.7000000000000001 0.6987951807228915]]


In [29]:
print (X_test)

[[0.0 1.0 0.0 0.6 0.6506024096385542]
 [1.0 0.0 0.0 0.74 0.8072289156626505]]
